export type Frequency = 'daily' | 'weekly' | 'monthly';
export type Scope = 'account' | 'character';
export type Priority = 'low' | 'medium' | 'high';
export type ClassGroup =
    | 'beginner'
    | 'journeyman'
    | 'maestro'
    | 'voidwalker'
    | 'warrior'
    | 'barbarian'
    | 'blood-berserker'
    | 'death-bringer'
    | 'squire'
    | 'divine-knight'
    | 'archer'
    | 'bowman'
    | 'siege-breaker'
    | 'hunter'
    | 'beast-master'
    | 'wind-walker'
    | 'mage'
    | 'wizard'
    | 'elemental-sorcerer'
    | 'shaman'
    | 'bubonic-conjurer'
    | 'arcane-cultist'
    | 'custom';

export type WorldFilter = 'all' | 'favorites' | 'character' | number;

export type TaskDefinition = {
    id: string;
    title: string;
    description?: string;
    world: number | 0;
    frequency: Frequency;
    scope: Scope;
    priority: Priority;
    requiresClasses?: ClassGroup[];
    optional?: boolean;
};
export type CharacterProfile = {
    id: string;
    name: string;
    classGroup: ClassGroup[];
    enabled: boolean;
    sortOrder: number;
};

export type CompletionRecord = {
    key: string;
    taskId: string;
    characterId: string | null;
    periodKey: string;
    completedAt: string;
};

export type Preferences = {
    hiddenTaskKeys: string[];
    favoriteTaskIds: string[];
    hideCompleted: boolean;
};

export const charactersSeed: CharacterProfile[] = [
    {
        id: 'char-1',
        name: 'Master Classes',
        classGroup: ['death-bringer', 'arcane-cultist', 'wind-walker'],
        enabled: true,
        sortOrder: 1,
    },
    {
        id: 'char-2',
        name: 'Divine Knight',
        classGroup: ['squire', 'divine-knight'],
        enabled: true,
        sortOrder: 2,
    },
    {
        id: 'char-3',
        name: 'VMAN',
        classGroup: ['voidwalker', 'maestro', 'journeyman'],
        enabled: true,
        sortOrder: 3,
    },
];

export const tasksSeed: TaskDefinition[] = [
    {
        id: 'quickref-daily-merit-tasks',
        title: 'Tasks: Daily Merit Tasks',
        description: 'Clear the daily merit board chores you care about.',
        world: 0,
        frequency: 'daily',
        scope: 'account',
        priority: 'low',
        optional: true,
    },
    {
        id: 'quickref-guild-daily-gp',
        title: 'Guild: Daily GP Tasks',
        description: 'Check and clear daily guild point tasks.',
        world: 0,
        frequency: 'daily',
        scope: 'account',
        priority: 'medium',
        optional: true,
    },
    {
        id: 'quickref-daily-bosskeys-tickets',
        title: 'EZ-Access: Boss Keys and Colosseum Tickets',
        description: 'Claim your daily boss keys and Colosseum tickets.',
        world: 0,
        frequency: 'daily',
        scope: 'account',
        priority: 'medium',
    },
    {
        id: 'w7-vendor-check',
        title: 'Vendor / Shop Check',
        description: 'Review daily-limited vendor purchases and shop rotations.',
        world: 7,
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
    },
    {
        id: 'account-weekly-happy-hour',
        title: 'Dungeon: Weekly Happy Hour',
        description: 'Run your weekly dungeon happy hour sessions.',
        world: 0,
        frequency: 'weekly',
        scope: 'account',
        priority: 'medium',
        optional: true,
    },
    {
        id: 'w1-free-pet-claim',
        title: 'Free Pet claim',
        description: 'Use your weekly free pet claim.',
        world: 1,
        frequency: 'weekly',
        scope: 'account',
        priority: 'medium',
        optional: true,
    },
    {
        id: 'w4-monthly-tome-nametags',
        title: 'Tome: Claim Nametags',
        description: 'Claim monthly Tome percentile rewards.',
        world: 4,
        frequency: 'monthly',
        scope: 'account',
        priority: 'high',
    },
    {
        id: 'character-printer-go-brrr',
        title: 'VMAN: Printer Go Brrr',
        description: 'Use free printer sample hours if available.',
        world: 0,
        frequency: 'daily',
        scope: 'character',
        priority: 'high',
        requiresClasses: ['maestro'],
    },
    {
        id: 'character-top-of-the-mornin-kills',
        title: 'Windwalker: Top of the Mornin Kills',
        description: 'Use your daily Top of the Mornin Kills.',
        world: 0,
        frequency: 'daily',
        scope: 'character',
        priority: 'high',
        requiresClasses: ['wind-walker'],
        optional: true,
    },
    {
        id: 'character-mc-discount',
        title: 'Masterclass: Daily Upgrades discount',
        description: 'Use your daily Masterclass Upgrades discount.',
        world: 0,
        frequency: 'daily',
        scope: 'character',
        priority: 'high',
        requiresClasses: ['wind-walker','death-bringer','arcane-cultist'],
    },
    {
        id: 'quickref-clicker-check',
        title: 'Clicker Games check. Orion, Poppy, Bubba',
        description: 'Check your 3 Clickers for progress / Upgrades.',
        world: 0,
        frequency: 'daily',
        scope: 'account',
        priority: 'medium',
    },
    {
        id: 'character-its-your-birthday',
        title: "VMAN: It's Your Birthday!",
        description: 'Use the daily beginner-class perk if relevant.',
        world: 0,
        frequency: 'daily',
        scope: 'character',
        priority: 'medium',
        requiresClasses: ['journeyman'],
        optional: true,
    },
    {
        id: 'character-void-trial-rerun',
        title: 'VMAN: Void Trial Rerun',
        description: 'Rerun your Voidwalker speedrun if relevant.',
        world: 0,
        frequency: 'weekly',
        scope: 'character',
        priority: 'medium',
        requiresClasses: ['voidwalker'],
    },
    {
        id: 'character-refinery-throttle',
        title: 'DK: Refinery Throttle',
        description: 'Use the daily refinery talent if available and still relevant.',
        world: 0,
        frequency: 'daily',
        scope: 'character',
        priority: 'low',
        requiresClasses: ['squire'],
        optional: true,
    },
    {
        id: 'w1-smithing-forge-anvil',
        title: 'Smithing: Forge and Anvil',
        description: 'Collect and refresh forge/anvil production.',
        world: 1,
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
    },
    {
        id: 'w1-picnic-stowaway',
        title: 'Picnic Stowaway Quest',
        description: 'Do the picnic daily if still useful for you.',
        world: 1,
        frequency: 'daily',
        scope: 'account',
        priority: 'low',
        optional: true,
    },
    {
        id: 'w1-baba-yaga',
        title: 'Miniboss: Baba Yaga',
        description: 'Do the Baba Yaga bosskill daily if still useful for you.',
        world: 1,
        frequency: 'daily',
        scope: 'account',
        priority: 'low',
        optional: true,
    },
        {
        id: 'w1-spike-minigame',
        title: 'Spike Minigame "if u love me let me go"',
        description: 'Do the Spike minigame hourly if still useful for you (Tome Highscore).',
        world: 1,
        frequency: 'daily',
        scope: 'account',
        priority: 'low',
        optional: true,
    },
    {
        id: 'w1-poopboss-and-boop',
        title: 'Miniboss: Dr Defecaus and Boops',
        description: 'Do the Dr Defecaus bosskill and the Boops daily if still useful for you.',
        world: 1,
        frequency: 'daily',
        scope: 'account',
        priority: 'low',
        optional: true,
    },
        {
        id: 'quickref-arcade-balls',
        title: 'Arcade Balls',
        description: 'Claim your arcade balls.',
        world: 0,
        frequency: 'daily',
        scope: 'account',
        priority: 'medium',
    },
    {
        id: 'w2-post-office',
        title: 'Post Office Orders',
        description: 'Spend or check your post office boxes.',
        world: 2,
        frequency: 'weekly',
        scope: 'account',
        priority: 'medium',
    },
    {
        id: 'quickref-alchemy-boron',
        title: 'Alchemy: Bubbles Boron',
        description: 'Spend your Boron/Atom Particles.',
        world: 0,
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
    },
    {
        id: 'quickref-alchemy-gems',
        title: 'Alchemy: Claim Gems from Liquid Shop',
        description: 'Spend your Boron/Atom Particles.',
        world: 0,
        frequency: 'daily',
        scope: 'account',
        priority: 'medium',
        optional: true,
    },
    {
        id: 'w2-alchemy-vials',
        title: 'Alchemy: Unlock Vials',
        description: 'Spend your Alchemy Vial unlock tries.',
        world: 2,
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
    },
    {
        id: 'quickref-alchemy-cost-reduction',
        title: 'Alchemy: Cost Reduction tokens',
        description: 'Buy and spend your Alchemy cost reduction tokens to level bubbles that you can Atom them.',
        world: 0,
        frequency: 'daily',
        scope: 'account',
        priority: 'medium',
    },
    {
        id: 'w2-killroy',
        title: 'Killroy',
        description: 'Use your weekly Killroy run if you are doing it.',
        world: 2,
        frequency: 'weekly',
        scope: 'account',
        priority: 'medium',
    },
    {
        id: 'w2-doot',
        title: 'Miniboss: Doot',
        description: 'Kill the Doot boss weekly for Candy and Gems.',
        world: 2,
        frequency: 'weekly',
        scope: 'account',
        priority: 'medium',
        optional: true,
    },
    {
        id: 'w2-biggie-hours',
        title: 'Miniboss: Biggie Hours',
        description: 'Kill the Biggie Hours boss weekly for Candy and Gems.',
        world: 2,
        frequency: 'weekly',
        scope: 'account',
        priority: 'medium',
        optional: true,
    },
    {
        id: 'w2-weekly-battle',
        title: 'Weekly Boss Battle',
        description: 'Weekly boss battle clear. https://docs.google.com/spreadsheets/d/1z1P2ouvYhe2pryWoF0kIQE7QichYpJt1GaPPos-e-aw',
        world: 2,
        frequency: 'weekly',
        scope: 'account',
        priority: 'medium',
    },
    {
        id: 'w2-vote',
        title: 'Bonus Ballot: Vote',
        description: 'Participate in the Bonus Ballot vote.',
        world: 2,
        frequency: 'weekly',
        scope: 'account',
        priority: 'medium',
        optional: true,
    },
    {
        id: 'w2-island-expeditions-daily',
        title: 'Island Expeditions: Bottles, Thrash and Crystals',
        description: 'Collect Bottles, Trash and kill Crystalsdaily.',
        world: 2,
        frequency: 'daily',
        scope: 'account',
        priority: 'medium',
    },
    {
        id: 'w2-island-expeditions-rando',
        title: 'Island Expeditions: Random weekly Boss',
        description: 'Kill the random weekly boss.',
        world: 2,
        frequency: 'weekly',
        scope: 'account',
        priority: 'medium',
    },
    {
        id: 'w2-island-expeditions-shimmer',
        title: 'Island Expeditions: Shimmer Island',
        description: 'Check and claim rewards from Shimmer Island.',
        world: 2,
        frequency: 'weekly',
        scope: 'account',
        priority: 'medium',
    },
    {
        id: 'quickref-construction',
        title: 'Construction: Build Queue Check',
        description: 'Review build queue.',
        world: 0,
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
    },
    {
        id: 'w3-refinery',
        title: 'Refinery: Rankup Check',
        description: 'Check if you can Rankup some Salts.',
        world: 3,
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
    },
    {
        id: 'w3-equinox',
        title: 'Equinox: Fill Bar status check',
        description: 'Check your Equinox Bar status.',
        world: 3,
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
    },
    {
        id: 'quickref-tiny-cogs-jeweled-cogs',
        title: 'Construction: Tiny and Jeweled Cogs',
        description: 'Check daily Tiny and Jeweled Cogs.',
        world: 0,
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
    },
    {
        id: 'w3-library',
        title: 'Library: Check and upgrade Talents',
        description: 'Check library count and upgrade talents.',
        world: 3,
        frequency: 'daily',
        scope: 'account',
        priority: 'low',
        optional: true,
    },
    {
        id: 'w3-trapping',
        title: 'Trapping: Claim Boxes',
        description: 'Collect your traps.',
        world: 3,
        frequency: 'daily',
        scope: 'account',
        priority: 'medium',
        optional: true,
    },
    {
        id: 'w3-trapping-setup',
        title: 'Trapping: New Box Setup',
        description: 'Refresh your trapping setup.',
        world: 3,
        frequency: 'monthly',
        scope: 'account',
        priority: 'medium',
    },
    {
        id: 'w3-worship-and-msa',
        title: 'Worship: MSA Charge Check',
        description: 'Weekly charge use.',
        world: 3,
        frequency: 'weekly',
        scope: 'account',
        priority: 'medium',
    },
    {
        id: 'w3-dilapidated-slush',
        title: 'Miniboss: Dilapidated Slush',
        description: 'Kill the Dilapidated Slush miniboss.',
        world: 3,
        frequency: 'weekly',
        scope: 'account',
        priority: 'medium',
    },
    {
        id: 'w3-worship-td',
        title: 'Worship TD Check',
        description: 'Monthly Worship tower defense check.',
        world: 3,
        frequency: 'monthly',
        scope: 'account',
        priority: 'medium',
    },
    {
        id: 'w4-breeding-eggs',
        title: 'Breeding: Hatch Eggs',
        description: 'Hatch breeding eggs.',
        world: 4,
        frequency: 'daily',
        scope: 'account',
        priority: 'medium',
    },
    {
        id: 'w4-cooking',
        title: 'Cooking: Check for Meal Upgrade',
        description: 'Check if you can upgrade any meals.',
        world: 4,
        frequency: 'daily',
        scope: 'account',
        priority: 'medium',
    },
    {
        id: 'w4-ribbons',
        title: 'Cooking: Ribbons',
        description: 'Check if you can combine Ribbons.',
        world: 4,
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
    },
    {
        id: 'w4-spices',
        title: 'Breeding:Daily Spice Claims',
        description: 'Daily Spice Claims.',
        world: 4,
        frequency: 'daily',
        scope: 'account',
        priority: 'medium',
        optional: true,
    },
        {
        id: 'w4-kitchen-upgrade',
        title: 'Cooking: Upgrade Kitchens',
        description: 'Check for any Kitchen Upgrades.',
        world: 4,
        frequency: 'daily',
        scope: 'account',
        priority: 'medium',
        optional: true,
    },
    {
        id: 'w4-chip-repository',
        title: 'Lab: Chip and Jewels Repository Rotation',
        description: 'Check weekly chip and jewels shop rotation.',
        world: 4,
        frequency: 'weekly',
        scope: 'account',
        priority: 'high',
    },
    {
        id: 'w4-mutated-mush',
        title: 'Miniboss: Mutated Mush',
        description: 'Kill the Mutated Mush miniboss.',
        world: 4,
        frequency: 'weekly',
        scope: 'account',
        priority: 'medium',
    },
    {
        id: 'w5-sailing',
        title: 'Sailing: Claim AFK Loot for each character',
        description: 'Claim loot, Spend treasure, do one character at a time and claim AFK Sailing time.',
        world: 5,
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
    },
    {
        id: 'w5-sailing-captains-shop',
        title: 'Sailing: Captains Shop',
        description: 'Check captain shop for Ender Captains.',
        world: 5,
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
    },
    {
        id: 'quickref-gaming',
        title: 'Gaming: Plants / Nuts / Nugget / Snail',
        description: 'Claim Nugget / Nuts / Upgrade Snail.',
        world: 0,
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
    },
    {
        id: 'w5-divinity-unlinks',
        title: 'Divinity: Unlinks / Relinks',
        description: 'Weekly divinity maintenance, if Dootless.',
        world: 5,
        frequency: 'weekly',
        scope: 'account',
        priority: 'medium',
        optional: true,
    },
    {
        id: 'w5-domeo-magmus',
        title: 'Miniboss: Domeo Magmus',
        description: 'Kill the Domeo Magmus miniboss.',
        world: 5,
        frequency: 'weekly',
        scope: 'account',
        priority: 'medium',
    },
    {
        id: 'w5-hole-camp',
        title: 'Hole: Check all Villagers Exp progress, invest Opals',
        description: 'Level up all Villagers, use Conjuror Points and level Studies.',
        world: 5,
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
    },
    {
        id: 'w5-hole-daily',
        title: 'Hole: Daily Check',
        description: 'Check Buckets for Opal, upgrade Bell, use String charge, use Lamp Wishes and destroy Jars.',
        world: 5,
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
    },
    {
        id: 'w5-hole-skill-caverns',
        title: 'Hole: Skill Caverns Layers',
        description: '5 Layers per Day, aim for min 35/30/35.',
        world: 5,
        frequency: 'daily',
        scope: 'account',
        priority: 'medium',
        optional: true,
    },
    {
        id: 'w5-hole-bravery',
        title: 'Hole: Bravery',
        description: 'Weekly Bravery run.',
        world: 5,
        frequency: 'weekly',
        scope: 'account',
        priority: 'high',
    },
    {
        id: 'w5-hole-justice',
        title: 'Hole: Justice',
        description: 'Weekly Justice run.',
        world: 5,
        frequency: 'weekly',
        scope: 'account',
        priority: 'high',
    },
    {
        id: 'w5-hole-wisdom',
        title: 'Hole: Wisdom',
        description: 'Weekly Wisdom run.',
        world: 5,
        frequency: 'weekly',
        scope: 'account',
        priority: 'high',
    },
    {
        id: 'w5-hole-dawg-den',
        title: 'Hole: Dawg Den',
        description: 'Try new Dawg Den Highscore with all 4 Classes (Beginner, Warrior, Archer, Mage).',
        world: 5,
        frequency: 'monthly',
        scope: 'account',
        priority: 'medium',
    },
    {
        id: 'w5-hole-gamibt',
        title: 'Hole: Gamibt',
        description: 'Push Gamibt summoning battles to 10M.',
        world: 5,
        frequency: 'monthly',
        scope: 'account',
        priority: 'low',
    },
    {
        id: 'w5-hole-gloomie',
        title: 'Hole: Gloomie Grotto',
        description: 'Push Gloomie Grotto deeper.',
        world: 5,
        frequency: 'monthly',
        scope: 'account',
        priority: 'medium',
    },
    {
        id: 'w5-hole-temple',
        title: 'Hole: Temple Golem',
        description: 'Push Temple Golem deeper.',
        world: 5,
        frequency: 'monthly',
        scope: 'account',
        priority: 'medium',
    },
    {
        id: 'w6-farming-daily',
        title: 'Farming: Crops / Megacrops',
        description: 'Day market upgrades, crop progression.',
        world: 6,
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
    },
    {
        id: 'w6-farming-reset',
        title: 'Farming: Reset and upgrade Night Market',
        description: 'Make sure to prepare various crops for reset to speed boost the reset.',
        world: 6,
        frequency: 'monthly',
        scope: 'account',
        priority: 'medium',
    },
    {
        id: 'w6-farming-exotic-market ',
        title: 'Farming: Exotic Market',
        description: 'Check and buy Upgrades from the Exotic Market.',
        world: 6,
        frequency: 'weekly',
        scope: 'account',
        priority: 'high',
    },
    {
        id: 'w6-sneaking',
        title: 'Sneaking: Jade / Floors Check',
        description: 'Review sneaking floors, jade, and ninja setup. Check Jade Emporium for upgrades.',
        world: 6,
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
    },
    {
        id: 'w6-summon-familiars',
        title: 'Summoning: Familiars',
        description: 'Weekly familiar claim/check.',
        world: 6,
        frequency: 'weekly',
        scope: 'account',
        priority: 'high',
    },
    {
        id: 'w6-summon-dailybattles',
        title: 'Summoning: Daily Battles',
        description: 'Use Daily summoning battles, if you are still early.',
        world: 6,
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
    },
    {
        id: 'w6-summon-push',
        title: 'Summoning: Push endless Summoning',
        description: 'Monthly endless summoning push, reset doublers via hole Lamp.',
        world: 6,
        frequency: 'monthly',
        scope: 'account',
        priority: 'high',
    },
    {
        id: 'w6-emporer',
        title: 'Emperor: Daily attempts',
        description: 'Use daily emperor attempts.',
        world: 6,
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
    },
    {
        id: 'w6-demented-spiritlord',
        title: 'Miniboss: Demented Spiritlord',
        description: 'Defeat the Demented Spiritlord.',
        world: 6,
        frequency: 'weekly',
        scope: 'account',
        priority: 'medium',
    },
    {
        id: 'quickref-spelunk-daily',
        title: 'Spelunking: Daily Check',
        description: 'Spend Amber on Upgrades, check Stamina charge.',
        world: 0,
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
    },
    {
        id: 'quickref-spelunk-pagereads',
        title: 'Spelunking: Daily Chapter Page reads',
        description: 'Use all your daily Chapter Page reads.',
        world: 0,
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
    },
    {
        id: 'w7-nametag',
        title: 'Unstable Reliquarium: Try a run for Nametag',
        description: 'Try an Unstable Reliquarium run to obtain the Nametag.',
        world: 7,
        frequency: 'weekly',
        scope: 'account',
        priority: 'high',
    },
    {
        id: 'w7-vote',
        title: 'Multi Meritocracy: Vote',
        description: 'Participate in the Multi Meritocracy vote.',
        world: 7,
        frequency: 'weekly',
        scope: 'account',
        priority: 'medium',
        optional: true,
    },
    {
        id: 'w7-research-daily',
        title: 'Research: Points / Observations / Grid Daily Check',
        description: 'Review observations, points, and the research grid.',
        world: 7,
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
    },
    {
        id: 'w7-minehead-daily',
        title: 'Minehead: Daily Check',
        description: 'Review Minehead claims and upgrades.',
        world: 7,
        frequency: 'daily',
        scope: 'account',
        priority: 'medium',
    },
    {
        id: 'w7-sushi-station-daily',
        title: 'Sushi Station: Daily Check',
        description: 'Review sushi combines, bucks, shakers and upgrades.',
        world: 7,
        frequency: 'daily',
        scope: 'account',
        priority: 'medium',
    },
    {
        id: 'w7-coral-reef-daily',
        title: 'Coral Reef: Daily Check',
        description: 'Review coral reef upgrades.',
        world: 7,
        frequency: 'daily',
        scope: 'account',
        priority: 'medium',
    },
];