export type Frequency = 'daily' | 'weekly' | 'monthly';
export type Scope = 'account' | 'character';
export type Priority = 'low' | 'medium' | 'high';
export type ResetGroup = 'daily-reset' | 'weekly-reset' | 'monthly-reset';
export type ClassGroup =
    | 'beginner'
    | 'warrior'
    | 'mage'
    | 'archer'
    | 'journeyman'
    | 'maestro'
    | 'voidwalker'
    | 'squire'
    | 'divine-knight'
    | 'custom';

export type WorldFilter = 'all' | 'favorites' | 'character' | number;

export type TaskDefinition = {
    id: string;
    title: string;
    description?: string;
    world: number | 0;
    system: string;
    category: string;
    frequency: Frequency;
    scope: Scope;
    priority: Priority;
    tags: string[];
    enabledByDefault: boolean;
    unlockWorld?: number;
    requiresClasses?: ClassGroup[];
    resetGroup: ResetGroup;
    optional?: boolean;
};

export type CharacterProfile = {
    id: string;
    name: string;
    classGroup: ClassGroup;
    enabled: boolean;
    sortOrder: number;
};

export type CompletionRecord = {
    key: string;
    taskId: string;
    characterId: string | null;
    periodKey: string;
    completedAt: string;
};

export type Preferences = {
    hiddenTaskIds: string[];
    favoriteTaskIds: string[];
    hideCompleted: boolean;
};

export const charactersSeed: CharacterProfile[] = [
    { id: 'char-1', name: 'Main DK', classGroup: 'divine-knight', enabled: true, sortOrder: 1 },
    { id: 'char-2', name: 'Voidwalker', classGroup: 'voidwalker', enabled: true, sortOrder: 2 },
    { id: 'char-3', name: 'Maestro', classGroup: 'maestro', enabled: true, sortOrder: 3 },
    { id: 'char-4', name: 'Squire', classGroup: 'squire', enabled: true, sortOrder: 4 },
];

export const tasksSeed: TaskDefinition[] = [
    {
        id: 'account-daily-merit-tasks',
        title: 'Daily Merit Tasks',
        description: 'Clear the daily merit board chores you care about.',
        world: 0,
        system: 'Global',
        category: 'Account',
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
        tags: ['merits', 'global'],
        enabledByDefault: true,
        resetGroup: 'daily-reset',
    },
    {
        id: 'account-guild-daily-gp',
        title: 'Guild Daily GP Tasks',
        description: 'Check and clear daily guild point tasks.',
        world: 0,
        system: 'Guild',
        category: 'Guild',
        frequency: 'daily',
        scope: 'account',
        priority: 'medium',
        tags: ['guild', 'gp'],
        enabledByDefault: true,
        resetGroup: 'daily-reset',
    },
    {
        id: 'account-vendor-check',
        title: 'Vendor / Shop Check',
        description: 'Review daily-limited vendor purchases and shop rotations.',
        world: 0,
        system: 'Global',
        category: 'Shops',
        frequency: 'daily',
        scope: 'account',
        priority: 'medium',
        tags: ['shop', 'vendors'],
        enabledByDefault: true,
        resetGroup: 'daily-reset',
        optional: true,
    },
    {
        id: 'account-weekly-happy-hour',
        title: 'Dungeon Happy Hour',
        description: 'Run your weekly dungeon happy hour sessions.',
        world: 0,
        system: 'Dungeon',
        category: 'Combat',
        frequency: 'weekly',
        scope: 'account',
        priority: 'medium',
        tags: ['dungeon', 'happy-hour'],
        enabledByDefault: true,
        resetGroup: 'weekly-reset',
    },
    {
        id: 'account-monthly-tome-nametags',
        title: 'Claim Tome Nametags',
        description: 'Claim monthly Tome percentile rewards.',
        world: 0,
        system: 'Tome',
        category: 'Rewards',
        frequency: 'monthly',
        scope: 'account',
        priority: 'medium',
        tags: ['tome', 'monthly'],
        enabledByDefault: true,
        resetGroup: 'monthly-reset',
    },
    {
        id: 'character-printer-go-brrr',
        title: 'Printer Go Brrr',
        description: 'Use free printer sample hours if available.',
        world: 0,
        system: 'Masterclass',
        category: 'Character Utility',
        frequency: 'daily',
        scope: 'character',
        priority: 'high',
        tags: ['printing', 'maestro', 'masterclass'],
        enabledByDefault: true,
        requiresClasses: ['maestro', 'voidwalker'],
        resetGroup: 'daily-reset',
    },
    {
        id: 'character-its-your-birthday',
        title: "It's Your Birthday!",
        description: 'Use the daily beginner-class perk if relevant.',
        world: 0,
        system: 'Beginner Class',
        category: 'Character Utility',
        frequency: 'daily',
        scope: 'character',
        priority: 'medium',
        tags: ['journeyman', 'maestro', 'voidwalker'],
        enabledByDefault: true,
        requiresClasses: ['journeyman', 'maestro', 'voidwalker'],
        resetGroup: 'daily-reset',
    },
    {
        id: 'character-void-trial-rerun',
        title: 'Void Trial Rerun',
        description: 'Rerun your daily Voidwalker speedrun if relevant.',
        world: 0,
        system: 'Masterclass',
        category: 'Character Utility',
        frequency: 'daily',
        scope: 'character',
        priority: 'medium',
        tags: ['voidwalker', 'speedrun'],
        enabledByDefault: true,
        requiresClasses: ['voidwalker'],
        resetGroup: 'daily-reset',
    },
    {
        id: 'character-refinery-throttle',
        title: 'Refinery Throttle',
        description: 'Use the daily refinery talent if available.',
        world: 0,
        system: 'Class Talent',
        category: 'Character Utility',
        frequency: 'daily',
        scope: 'character',
        priority: 'medium',
        tags: ['squire', 'refinery'],
        enabledByDefault: true,
        requiresClasses: ['squire'],
        resetGroup: 'daily-reset',
    },
    {
        id: 'w1-smithing-forge-anvil',
        title: 'Smithing Forge and Anvil',
        description: 'Collect and refresh forge/anvil production.',
        world: 1,
        system: 'Smithing',
        category: 'Skilling',
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
        tags: ['w1', 'smithing'],
        enabledByDefault: true,
        unlockWorld: 1,
        resetGroup: 'daily-reset',
    },
    {
        id: 'w1-picnic-stowaway',
        title: 'Picnic Stowaway Daily Quest',
        description: 'Do the picnic daily if still useful for you.',
        world: 1,
        system: 'Blunder Hills',
        category: 'Quest',
        frequency: 'daily',
        scope: 'account',
        priority: 'medium',
        tags: ['w1', 'quest'],
        enabledByDefault: true,
        unlockWorld: 1,
        resetGroup: 'daily-reset',
        optional: true,
    },
    {
        id: 'w2-post-office',
        title: 'Post Office Orders',
        description: 'Spend or check your post office boxes.',
        world: 2,
        system: 'Post Office',
        category: 'Skilling',
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
        tags: ['w2', 'post-office'],
        enabledByDefault: true,
        unlockWorld: 2,
        resetGroup: 'daily-reset',
    },
    {
        id: 'w2-alchemy',
        title: 'Alchemy Bubbles / Vials / Sigils',
        description: 'Review bubbles, liquids, vials, and sigils.',
        world: 2,
        system: 'Alchemy',
        category: 'Skilling',
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
        tags: ['w2', 'alchemy'],
        enabledByDefault: true,
        unlockWorld: 2,
        resetGroup: 'daily-reset',
    },
    {
        id: 'w2-killroy',
        title: 'Killroy',
        description: 'Use your daily Killroy run if you are doing it.',
        world: 2,
        system: 'Killroy',
        category: 'Combat',
        frequency: 'daily',
        scope: 'account',
        priority: 'medium',
        tags: ['w2', 'killroy'],
        enabledByDefault: true,
        unlockWorld: 2,
        resetGroup: 'daily-reset',
    },
    {
        id: 'w2-weekly-battle',
        title: 'Weekly Battle',
        description: 'Main weekly battle clear.',
        world: 2,
        system: 'Weekly Battle',
        category: 'Combat',
        frequency: 'weekly',
        scope: 'account',
        priority: 'medium',
        tags: ['w2', 'weekly-battle'],
        enabledByDefault: true,
        unlockWorld: 2,
        resetGroup: 'weekly-reset',
    },
    {
        id: 'w3-construction',
        title: 'Construction Queue Check',
        description: 'Review build queue, cogs, and priorities.',
        world: 3,
        system: 'Construction',
        category: 'Skilling',
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
        tags: ['w3', 'construction'],
        enabledByDefault: true,
        unlockWorld: 3,
        resetGroup: 'daily-reset',
    },
    {
        id: 'w3-trapping',
        title: 'Trapping Boxes',
        description: 'Collect or refresh your trapping setup.',
        world: 3,
        system: 'Trapping',
        category: 'Skilling',
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
        tags: ['w3', 'trapping'],
        enabledByDefault: true,
        unlockWorld: 3,
        resetGroup: 'daily-reset',
    },
    {
        id: 'w3-worship-and-msa',
        title: 'Worship / MSA Charge Check',
        description: 'Weekly charge and tower defense maintenance.',
        world: 3,
        system: 'Worship',
        category: 'Skilling',
        frequency: 'weekly',
        scope: 'account',
        priority: 'medium',
        tags: ['w3', 'worship'],
        enabledByDefault: true,
        unlockWorld: 3,
        resetGroup: 'weekly-reset',
    },
    {
        id: 'w4-breeding-eggs',
        title: 'Breeding Eggs',
        description: 'Collect, hatch, and queue up eggs.',
        world: 4,
        system: 'Breeding',
        category: 'Skilling',
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
        tags: ['w4', 'breeding'],
        enabledByDefault: true,
        unlockWorld: 4,
        resetGroup: 'daily-reset',
    },
    {
        id: 'w4-spices',
        title: 'Spices / Kitchen Setup',
        description: 'Check kitchen production and spice setup.',
        world: 4,
        system: 'Cooking',
        category: 'Skilling',
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
        tags: ['w4', 'cooking'],
        enabledByDefault: true,
        unlockWorld: 4,
        resetGroup: 'daily-reset',
    },
    {
        id: 'w4-chip-repository',
        title: 'Chip Repository Rotation',
        description: 'Check weekly chip shop rotation.',
        world: 4,
        system: 'Laboratory',
        category: 'Shops',
        frequency: 'weekly',
        scope: 'account',
        priority: 'high',
        tags: ['w4', 'lab', 'chips'],
        enabledByDefault: true,
        unlockWorld: 4,
        resetGroup: 'weekly-reset',
    },
    {
        id: 'w4-jewel-spinner',
        title: 'Jewel Spinner Rotation',
        description: 'Check weekly jewel spinner rotation.',
        world: 4,
        system: 'Laboratory',
        category: 'Shops',
        frequency: 'weekly',
        scope: 'account',
        priority: 'high',
        tags: ['w4', 'lab', 'jewels'],
        enabledByDefault: true,
        unlockWorld: 4,
        resetGroup: 'weekly-reset',
    },
    {
        id: 'w5-sailing',
        title: 'Sailing Ships / Treasures / Captain Shop',
        description: 'Spend treasure, claim loot, and manage captains.',
        world: 5,
        system: 'Sailing',
        category: 'Skilling',
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
        tags: ['w5', 'sailing'],
        enabledByDefault: true,
        unlockWorld: 5,
        resetGroup: 'daily-reset',
    },
    {
        id: 'w5-gaming',
        title: 'Gaming Plants / Imports / Upgrades',
        description: 'Review imports and active gaming setup.',
        world: 5,
        system: 'Gaming',
        category: 'Skilling',
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
        tags: ['w5', 'gaming'],
        enabledByDefault: true,
        unlockWorld: 5,
        resetGroup: 'daily-reset',
    },
    {
        id: 'w5-divinity-unlinks',
        title: 'Divinity Unlinks / Relinks',
        description: 'Weekly divinity maintenance.',
        world: 5,
        system: 'Divinity',
        category: 'Skilling',
        frequency: 'weekly',
        scope: 'account',
        priority: 'medium',
        tags: ['w5', 'divinity'],
        enabledByDefault: true,
        unlockWorld: 5,
        resetGroup: 'weekly-reset',
    },
    {
        id: 'w6-farming',
        title: 'Farming Crops / Crossbreeds / Megacrops',
        description: 'Review fields, tickets, and crop progression.',
        world: 6,
        system: 'Farming',
        category: 'Skilling',
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
        tags: ['w6', 'farming'],
        enabledByDefault: true,
        unlockWorld: 6,
        resetGroup: 'daily-reset',
    },
    {
        id: 'w6-sneaking',
        title: 'Sneaking / Jade / Floors Check',
        description: 'Review sneaking floors, jade, and ninja setup.',
        world: 6,
        system: 'Sneaking',
        category: 'Skilling',
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
        tags: ['w6', 'sneaking'],
        enabledByDefault: true,
        unlockWorld: 6,
        resetGroup: 'daily-reset',
    },
    {
        id: 'w6-jade-emporium',
        title: 'Jade Emporium',
        description: 'Check jade purchases and progression items.',
        world: 6,
        system: 'Jade Emporium',
        category: 'Shops',
        frequency: 'daily',
        scope: 'account',
        priority: 'medium',
        tags: ['w6', 'jade'],
        enabledByDefault: true,
        unlockWorld: 6,
        resetGroup: 'daily-reset',
    },
    {
        id: 'w6-familiars',
        title: 'Familiars',
        description: 'Weekly familiar claim/check.',
        world: 6,
        system: 'Summoning',
        category: 'Rewards',
        frequency: 'weekly',
        scope: 'account',
        priority: 'medium',
        tags: ['w6', 'familiars'],
        enabledByDefault: true,
        unlockWorld: 6,
        resetGroup: 'weekly-reset',
    },
    {
        id: 'w7-research',
        title: 'Research Points / Observations / Grid Check',
        description: 'Review observations, points, and the research grid.',
        world: 7,
        system: 'Research',
        category: 'Skilling',
        frequency: 'daily',
        scope: 'account',
        priority: 'high',
        tags: ['w7', 'research'],
        enabledByDefault: true,
        unlockWorld: 7,
        resetGroup: 'daily-reset',
    },
    {
        id: 'w7-minehead',
        title: 'Minehead Check',
        description: 'Review Minehead claims and upgrades.',
        world: 7,
        system: 'Minehead',
        category: 'Skilling',
        frequency: 'daily',
        scope: 'account',
        priority: 'medium',
        tags: ['w7', 'minehead'],
        enabledByDefault: true,
        unlockWorld: 7,
        resetGroup: 'daily-reset',
    },
    {
        id: 'w7-sushi-station',
        title: 'Sushi Station Check',
        description: 'Review sushi combines, bucks, and upgrades.',
        world: 7,
        system: 'Sushi Station',
        category: 'Skilling',
        frequency: 'daily',
        scope: 'account',
        priority: 'medium',
        tags: ['w7', 'sushi'],
        enabledByDefault: true,
        unlockWorld: 7,
        resetGroup: 'daily-reset',
    },
];
